language: python
python:
- '3.5'
- '3.6'
install:
- pip install .
script:
- python -m pytest tests/
deploy:
  provider: pypi
  user: witlox
  password:
    secure: xUdCnDFbwIP5Oq3AuPvPIHsMgMz+f7D7uDjsgdVVgRHLjNOgRoIYjmuUvHDD46hqdp3N8TTPEYvLKdwPBJFr7hdGHAN0g7s+3v+fE/O6iwKSTCmHYRbQ9YwBhiT4SifFjjqm1GydiwloZmJrrfChMr1msnE5tpRJ9ZoNa4PL1T1zy4Om+qqtJ46QJOcHLLpU5Gk/MhAXSmofn5Zh239UeN+SUsRa4cuoJGvNUY3ekfIcmeN42aw4uTfGnyouZRvlhP02aiu1dkkXDqJmiBhGKjDx6WLz8uXWEeWpURe2Fd7H58RiigBgsbgerEbYI9F8NjcEOzFw1Na1HMEXBnszhL58TJU8PVTolLAVYw8/Hwhl0vX7QEMxoN6RF0urLBDPGBM5irmA7aMQxZ8p7zDU7gE58GtVATyuOK4MQJB46N8IREyr+Ijlj8L98BwXk30OAZRjcNwYObX26FfXlHUaIKn80ieiuhfQ2Djy8+39mdxUEZhw9NXyX+rN9L/ah8MfSgE4+Y5nyBBmcQ8YDte2bVa9JyXwd0UAbvkIxN66b4NQvrMjbzDSu0uUvFepU72HZp0YhQn0yX0iO5FEgzxS/19jfKLBCFcB+BuK7nKFGEY+4jMSDxQQp0oX7UYhLFM2bS0+PSDsm6KT/G/4lSAbwQhiuKHimCIAVRsZ2+LzN/o=
